# Generated by Django 5.2.14 on 2026-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[('MEETING_CREATED', 'Meeting Created'), ('MEETING_STARTED', 'Meeting Started'), ('MEETING_ENDED', 'Meeting Ended'), ('PARTICIPANT_JOINED', 'Participant Joined'), ('PARTICIPANT_LEFT', 'Participant Left'), ('RECORDING_READY', 'Recording Ready'), ('RECORDING_COMPLETED', 'Recording Completed'), ('TRANSCRIPT_READY', 'Transcript Ready'), ('TRANSCRIPT_COMPLETED', 'Transcript Completed'), ('SUMMARY_READY', 'Summary Ready'), ('SUMMARY_COMPLETED', 'Summary Completed'), ('YOUTUBE_UPLOAD_COMPLETED', 'YouTube Upload Completed')], max_length=50),
        ),
    ]
