# Generated by Django 5.2.14 on 2026-06-23 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0004_alter_meetingrecording_meeting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEETING_INVITE', 'Meeting Invite'), ('MEETING_START', 'Meeting Start'), ('MEETING_REMINDER', 'Meeting Reminder'), ('RECORDING_READY', 'Recording Ready'), ('TRANSCRIPT_READY', 'Transcript Ready'), ('SUMMARY_READY', 'Summary Ready'), ('TASK_ASSIGNED', 'Task Assigned'), ('YOUTUBE_UPLOADED', 'YouTube Upload Complete'), ('MESSAGE', 'New Message')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
