# Generated by Django 5.2.14 on 2026-06-23 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meetingrecording_meeting'),
        ('summaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('NOTE', 'Note'), ('HIGHLIGHT', 'Discussion Highlight'), ('QUESTION', 'Question')], default='NOTE', max_length=20)),
                ('is_resolved', models.BooleanField(default=False, help_text='For questions - marks if answered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notes', to='meetings.meeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
