# Generated by Django 5.2.14 on 2026-06-23 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0005_meetingrecording_is_uploaded_to_youtube_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('is_uploaded_to_youtube', models.BooleanField(default=False)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_visibility', models.CharField(blank=True, choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meeting')),
            ],
        ),
    ]
