# Generated by Django 5.2.14 on 2026-06-12 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meetingparticipant',
            name='unique_meeting_user_participant',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('INSTANT', 'Instant Meeting'), ('SCHEDULED', 'Scheduled Meeting'), ('RECURRING', 'Recurring Meeting'), ('LINK_GENERATION', 'Meeting Link Generation'), ('ID_GENERATION', 'Meeting ID Generation')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'user')},
        ),
    ]
