# Generated by Django 5.2.14 on 2026-06-20 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrecording',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_recordings', to='meetings.meeting'),
        ),
    ]
