# Generated by Django 5.2.14 on 2026-06-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meetingrecording_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrecording',
            name='is_uploaded_to_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingrecording',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingrecording',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meetingrecording',
            name='youtube_visibility',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=20),
        ),
    ]
